### PR TITLE
feat: Support ESLint 7.x

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

(dev)Dependencies should be compatible with ESLint 7 too before we can merge this one:

- [x] [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import/issues/1772)
  - [x]  [PR](https://github.com/benmosher/eslint-plugin-import/pull/1715) + [commit](https://github.com/benmosher/eslint-plugin-import/commit/6a110dd16a7fd775f08601054bf14ffd503eea7b)
  - [x]  [Release](https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md#2211---2020-06-07)
- [x] [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest/issues/568)
  - [x]  [PR](https://github.com/jest-community/eslint-plugin-jest/pull/572)
  - [x]  Released
- [x] [`eslint-plugin-jest-dom`](https://github.com/testing-library/eslint-plugin-jest-dom/issues/45)
  - [x]  [PR](https://github.com/testing-library/eslint-plugin-jest-dom/pull/46)
  - [x]  [Release](https://github.com/testing-library/eslint-plugin-jest-dom/releases/tag/v3.0.0)
- [x] [`eslint-plugin-jsx-a11y`](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/683)
  - [x]  [PR](https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/684)
  - [x]  [Release](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/CHANGELOG.md#630--2020-06-18)
- [x] `eslint-plugin-react`
  - [x]  [PR](https://github.com/yannickcr/eslint-plugin-react/pull/2635)
  - [x]  [Release](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.20.0)
- [x] [`eslint-plugin-react-hooks`](https://github.com/facebook/react/issues/18876)
  - [x]  [PR 1](https://github.com/facebook/react/pull/18878)
  - [x] [PR 2](https://github.com/facebook/react/pull/18897)
  - [x]  [Release](https://github.com/facebook/react/commit/9f396bdd5d64be4ba02f0e74e12b686b626c3f1d)
- [x] [`eslint-plugin-testing-library`](https://github.com/testing-library/eslint-plugin-testing-library/issues/138)
  - [x]  [PR](https://github.com/testing-library/eslint-plugin-testing-library/pull/139)
  - [x]  [Released](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v3.9.0)
- [x] [`eslint-find-rules`](https://github.com/sarbbottam/eslint-find-rules/issues/318)
  - [x]  [PR](https://github.com/sarbbottam/eslint-find-rules/pull/319)
  - [x]  [Release](https://github.com/sarbbottam/eslint-find-rules/pull/321)

---

BREAKING CHANGE: Requires Node@^10.12.x || 12.x
BREAKING CHANGE: Requires ESLint@^7.x

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@kentcdodds It seems like `kcd-scripts` is taking the wrong `eslint` version (the one installed by `kcd-scripts` instead of by `eslint-config-kentcdodds`) to execute the `lint` script.

**Comment by kentcdodds** [comment]
There's a circular dependency. We'll need to update both. I don't mind if it's messed up for one release, so the order shouldn't matter.

**Comment by MichaelDeBoey** [comment]
@kentcdodds Let's first update this one then 🙂

I still have another problem.
Due to the fact that all Node.js/CommonJS rules [have been deprecated](https://eslint.org/docs/user-guide/migrating-to-7.0.0#deprecate-node-rules), I included `eslint-plugin-node` to replace them.
But this means I have to include all the following rules too:
```sh
node/exports-style                             node/file-extension-in-import                  node/no-callback-literal                       node/no-deprecated-api                         node/no-exports-assign
node/no-extraneous-import                      node/no-extraneous-require                     node/no-missing-import                         node/no-missing-require                        node/no-restricted-import
node/no-restricted-require                     node/no-unpublished-bin                        node/no-unpublished-import                     node/no-unpublished-require                    node/no-unsupported-features/es-builtins
node/no-unsupported-features/es-syntax         node/no-unsupported-features/node-builtins     node/prefer-global/buffer                      node/prefer-global/console                     node/prefer-global/process
node/prefer-global/text-decoder                node/prefer-global/text-encoder                node/prefer-global/url                         node/prefer-global/url-search-params           node/prefer-promises/dns
node/prefer-promises/fs                        node/process-exit-as-throw                     node/shebang
```

Should I include all `node` rules or just remove all Node.js/CommonJS rules? 🤔

**Comment by kentcdodds** [comment]
Let's go ahead and configure those rules 👍

**Review by kentcdodds — APPROVED** [review]
Looks awesome! Thanks so much for all your work here!

**Comment by MichaelDeBoey** [comment]
Always a pleasure to help out 🙂

**Comment by MichaelDeBoey** [comment]
@kentcdodds Since CI is failing tests, this one won't be released either 😕
https://travis-ci.com/github/kentcdodds/eslint-config-kentcdodds/builds/185492446

**Pull request merged**
