### PR TITLE
feat: update `eslint-plugin-testing-library`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
`eslint-plugin-testing-library` v4.0.0 is [released](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v4.0.0) 🎉

Should we do something with the [shared settings](https://github.com/testing-library/eslint-plugin-testing-library#shared-settings) or should we keep the default? 🤔

I also updated all other dependencies to latest minor

---

BREAKING CHANGE: `eslint-plugin-testing-library` will now [report aggressively](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/migrating-to-v4-guide.md#aggressive-reporting)

CC/ @Belco90

### CODE REVIEW

**Comment by Belco90** [comment]
I'd say you shouldn't have to set any shared settings, it will work fine for most of the users out of the box.

Not sure if you want to enable all available rules tho 😅

**Comment by MichaelDeBoey** [comment]
@Belco90 We have checks in this repo to check whether all rules of the used ESLint plugins are at least set to `off`, so that's why we need to include all rules separately.

I've been looking into the new rules and what @kentcdodds recommended in his ["Common mistakes with React Testing Library" blogpost](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library) to make the choice of setting the rules to `off`, `warn` or `error`.
We can still decide to disable/warn for a certain rule.

**Comment by Belco90** [comment]
That's absolutely up to you! Just saying that I'm not sure if you are interested in every single one of them.

**Review by kentcdodds — APPROVED** [review]
Looks great to me! Thanks!

**Pull request merged**
