### PR TITLE
fix: Fix peerDependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by MichaelDeBoey** [comment]
@kentcdodds Tests will still fail until this one's merged into `kcd-scripts` or we fix `resolveBin` util over there

**Comment by kentcdodds** [comment]
I fixed the problem once and for all :) https://github.com/kentcdodds/eslint-config-kentcdodds/commit/d585bd5c3f211ac7ba541c27788e05893296d67d

**Comment by MichaelDeBoey** [comment]
@kentcdodds That will break `prettier` config though 😕😢
https://github.com/kentcdodds/eslint-config-kentcdodds/blob/master/.prettierrc.js

**Comment by kentcdodds** [comment]
😆

I can't win! Maybe I'll make kcd-scripts a peerDep then.

**Comment by kentcdodds** [comment]
Or wait... Nah, I'll just copy/paste the prettier config.

**Comment by MichaelDeBoey** [comment]
Or we could have a look into the `resolveBin` function to make sure it takes the locally installed version before the version installed by `kcd-scripts`/other dependencies? 🤔

**Comment by kentcdodds** [comment]
Nah, I don't think copy/pasting the prettier config is all that big of a deal and I do think it's better to avoid the circular dependency, so I don't want to bring back kcd-scripts here.

**Comment by MichaelDeBoey** [comment]
We have circular dependencies for al lot of other dependencies of `kcd-scripts` though 🤔

**Comment by kentcdodds** [comment]
We do? What else does kcd-scripts depend on that depends on it as well?

**Comment by MichaelDeBoey** [comment]
I know for sure about `cross-env`, all `@testing-library` packages
Other I would have to check

**Comment by kentcdodds** [comment]
No, that's different. In those cases those packages depend on things which kcd-scripts also depends on.

I'm talking about this case where the eslint config had a dep on kcd-scripts and kcd-scripts had a dep on the eslint config. That's what I want to avoid. That's a circular dependency.

**Comment by MichaelDeBoey** [comment]
I don't think there are others in the same case

**Pull request merged**
