### PR TITLE
Update package.json

### LINKED ISSUE #29: babel/camelcase rule not found
Screenshot 2019-04-14 at 10 25 32 PM

### PR DESCRIPTION
**Pull request by huchenme**
Closes #29

### CODE REVIEW

**Comment by huchenme** [comment]
Could you merge and release please?

**Comment by kentcdodds** [comment]
The build failed

**Comment by kentcdodds** [comment]
you'll have to wait until tomorrow or sometime this week when I can give it a look and get it fixed. Or you can figure out what's wrong and fix it yourself.

**Comment by kentcdodds** [comment]
Also, while I'm fine with people using this please remember that this is a project for myself 😅

**Comment by huchenme** [comment]
@kentcdodds sure, I might need to migrate to my own config settings sometimes :) 
by the way, fixed the build issue, Travis automatically use latest version which include new rules, I have turned on `jest/no-empty-title`, feel free to turn it off.

Do you consider to lock the version in some ways? (yarn lock file or use exact version maybe?)

**Comment by kentcdodds** [comment]
I'm fine with current process 👍 thank you!

**Pull request merged**
